// Section configuration (fully migrated from builder-constants.ts)
// All section metadata and toggles should be maintained here. Do not duplicate in builder-constants.ts.
export const SECTION_CONFIG = [
  // Core Required Sections
  {
    key: 'home',
    label: 'Home',
    description: 'Hero section showing your names, love message, and anniversary.',
    icon: '🏠',
    preview: 'hero-preview',
    required: true,
    defaultEnabled: true,
  },
  // Content Sections
  {
    key: 'love_letter',
    label: 'Love Letter',
    description: 'Your heartfelt message to your partner',
    icon: '💌',
    preview: 'letter-preview',
    required: false,
    defaultEnabled: true,
  },
  {
    key: 'our_story',
    label: 'Our Story',
    description: 'Share your relationship story in detail',
    icon: '📖',
    preview: 'story-preview',
    required: false,
    defaultEnabled: false,
  },
  // Timeline - Now handles first date, milestones, special moments
  {
    key: 'timeline',
    label: 'Timeline',
    description: 'Show the important moments of your love story (includes first date, milestones, special moments)',
    icon: '📅',
    preview: 'timeline-preview',
    required: false,
    defaultEnabled: true,
  },
  // Photo Sections - Gallery now supports grid, polaroid, carousel layouts
  {
    key: 'gallery',
    label: 'Gallery',
    description: 'Display photos from your relationship journey (grid, polaroid, or carousel)',
    icon: '📸',
    preview: 'gallery-preview',
    required: false,
    defaultEnabled: true,
  },
  // Music & Video
  {
    key: 'song',
    label: 'Song',
    description: 'Embed your special Spotify or YouTube song.',
    icon: '🎵',
    preview: 'song-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'playlist',
    label: 'Playlist',
    description: 'Share your relationship playlist',
    icon: '🎶',
    preview: 'playlist-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'video_memories',
    label: 'Video Memories',
    description: 'Share embedded video memories',
    icon: '🎬',
    preview: 'video-preview',
    required: false,
    defaultEnabled: false,
  },
  // Stats & Counters
  {
    key: 'relationship_stats',
    label: 'Relationship Stats',
    description: 'Show days, months, and hours together',
    icon: '📊',
    preview: 'stats-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'anniversary_countdown',
    label: 'Anniversary Countdown',
    description: 'Live countdown to your next anniversary',
    icon: '⏰',
    preview: 'countdown-preview',
    required: false,
    defaultEnabled: false,
  },
  // Dreams & Future
  {
    key: 'future_dreams',
    label: 'Future Dreams',
    description: 'Share your plans and dreams together',
    icon: '💭',
    preview: 'dreams-preview',
    required: false,
    defaultEnabled: false,
  },
  // Interactive Sections
  {
    key: 'quotes',
    label: 'Love Quotes',
    description: 'Display romantic love quotes',
    icon: '💕',
    preview: 'quotes-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'reasons_love_you',
    label: 'Reasons I Love You',
    description: 'List all the reasons you love them',
    icon: '💖',
    preview: 'reasons-preview',
    required: false,
    defaultEnabled: false,
  },
  // Guest & Messages
  {
    key: 'guest_messages',
    label: 'Guest Messages',
    description: 'Let friends and family leave messages',
    icon: '💬',
    preview: 'guest-preview',
    required: false,
    defaultEnabled: false,
  },
  // Special Features
  {
    key: 'letter_future',
    label: 'Letter to the Future',
    description: 'Write a message to open later',
    icon: '📮',
    preview: 'future-letter-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'gift_section',
    label: 'Gift Section',
    description: 'Display digital love gifts',
    icon: '🎁',
    preview: 'gift-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'surprise_message',
    label: 'Surprise Message',
    description: 'Hidden message reveal feature',
    icon: '🎉',
    preview: 'surprise-preview',
    required: false,
    defaultEnabled: false,
  },
  // Keepsake
  {
    key: 'qr_keepsake',
    label: 'QR Keepsake',
    description: 'A printable QR code card for physical keepsake',
    icon: '🎴',
    preview: 'qr-preview',
    required: false,
    defaultEnabled: false,
  },
  // Optional: Memory Map
  {
    key: 'memory_map',
    label: 'Memory Map',
    description: 'Show places you have visited together',
    icon: '🗺️',
    preview: 'map-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'birthday_message',
    label: 'Birthday Message',
    description: 'A personal birthday greeting for the celebrant',
    icon: '🎂',
    preview: 'birthday-message-preview',
    required: false,
    defaultEnabled: true,
  },
  {
    key: 'birthday_wishes',
    label: 'Birthday Wishes',
    description: 'Messages from friends and family to celebrate the birthday',
    icon: '🎈',
    preview: 'birthday-wishes-preview',
    required: false,
    defaultEnabled: true,
  },
  {
    key: 'birthday_countdown',
    label: 'Birthday Countdown',
    description: 'Live countdown timer to the birthday celebration',
    icon: '⏳',
    preview: 'birthday-countdown-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'birthday_timeline',
    label: 'Birthday Timeline',
    description: 'Highlight life milestones and memories for the celebrant',
    icon: '🎂',
    preview: 'birthday-timeline-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'party_details',
    label: 'Party Details',
    description: 'Set time, venue and dress code for the celebration',
    icon: '📍',
    preview: 'party-details-preview',
    required: false,
    defaultEnabled: false,
  },
  {
    key: 'gift_wishlist',
    label: 'Gift Wishlist',
    description: 'Share gift ideas and wishlist for the birthday',
    icon: '🎁',
    preview: 'gift-wishlist-preview',
    required: false,
    defaultEnabled: false,
  },
];
