import type { Section } from '@/lib/types';

type SiteTypeConfigEntry = {
  label: string;
  icon: string;
  description: string;
  sections: Section[];
};

// Keep site type section lists aligned with the canonical Section union.
export const SITE_TYPE_CONFIG = {
  couple: {
    label: 'Couple',
    icon: '💕',
    description: 'Celebrate your love story.',
    sections: [
      'home',
      'love_letter',
      'timeline',
      'gallery',
      'playlist',
      'qr_keepsake',
      'quotes',
      'future_dreams',
      'video_memories',
      'memory_map',
      'surprise_message',
      'relationship_stats',
      'anniversary_countdown',
      'letter_future',
      'gift_section',
      'reasons_love_you',
      'guest_messages',
    ],
  },

  birthday: {
    label: 'Birthday',
    icon: '🎂',
    description: 'Make birthdays memorable.',
    sections: [
      'home',
      'gallery',
      'birthday_countdown',
      'birthday_wishes',
      'playlist',
      'qr_keepsake',
      'video_memories',
      'memory_map',
      'surprise_message',
      'birthday_message',
      'party_details',
      'gift_wishlist',
      'birthday_timeline',
      'guest_messages',
    ],
  },

  wedding: {
    label: 'Wedding',
    icon: '💍',
    description: 'Share your special wedding day.',
    sections: [
      'home',
      'our_story',
      'gallery',
      'wedding_countdown',
      'event_details',
      'playlist',
      'qr_keepsake',
      'video_memories',
      'memory_map',
      'guest_messages',
      'wedding_timeline',
      'gift_registry',
      'rsvp',
      'couple_message',
    ],
  },

  anniversary: {
    label: 'Anniversary',
    icon: '🌹',
    description: 'Celebrate another meaningful year together.',
    sections: [
      'home',
      'love_letter',
      'timeline',
      'gallery',
      'playlist',
      'anniversary_countdown',
      'video_memories',
      'memory_map',
      'surprise_message',
      'relationship_stats',
      'guest_messages',
      'future_dreams',
      'gift_section',
    ],
  },

  graduation: {
    label: 'Graduation',
    icon: '🎓',
    description: 'Celebrate academic achievements and memories.',
    sections: [
      'home',
      'gallery',
      'graduation_message',
      'countdown',
      'school_memories',
      'video_memories',
      'guest_messages',
      'achievements',
      'future_plans',
      'playlist',
      'qr_keepsake',
    ],
  },

  baby_shower: {
    label: 'Baby Shower',
    icon: '🍼',
    description: 'Celebrate the upcoming arrival of a little one.',
    sections: [
      'home',
      'gallery',
      'countdown',
      'event_details',
      'guest_messages',
      'gift_registry',
      'playlist',
      'video_memories',
      'memory_map',
      'baby_predictions',
      'parents_message',
    ],
  },

  baptism: {
    label: 'Baptism',
    icon: '👶',
    description: 'Celebrate a baptism ceremony and welcome the child.',
    sections: [
      'home',
      'invitation',
      'gallery',
      'event_details',
      'schedule',
      'dress_code',
      'map_section',
      'rsvp',
      'parents_message',
      'guest_messages',
      'playlist',
      'photo_highlights',
      'video_memories',
    ],
  },

  debut: {
    label: 'Debut',
    icon: '👑',
    description: 'Make an 18th birthday or debut celebration extra special.',
    sections: [
      'home',
      'gallery',
      'countdown',
      'event_details',
      'playlist',
      'video_memories',
      'guest_messages',
      'birthday_wishes',
      'photo_highlights',
      'celebrant_message',
      'gift_wishlist',
    ],
  },

  memorial: {
    label: 'Memorial',
    icon: '🕊️',
    description: 'Honor and remember a loved one.',
    sections: [
      'home',
      'gallery',
      'life_story',
      'tributes',
      'video_memories',
      'memory_map',
      'guest_messages',
      'photo_highlights',
      'family_message',
    ],
  },

  family: {
    label: 'Family',
    icon: '🏡',
    description: 'Capture family memories and milestones.',
    sections: [
      'home',
      'gallery',
      'timeline',
      'video_memories',
      'memory_map',
      'playlist',
      'quotes',
      'guest_messages',
      'family_message',
      'photo_highlights',
    ],
  },

  friendship: {
    label: 'Friendship',
    icon: '🫶',
    description: 'Celebrate friendship and shared memories.',
    sections: [
      'home',
      'gallery',
      'timeline',
      'playlist',
      'quotes',
      'video_memories',
      'memory_map',
      'surprise_message',
      'guest_messages',
      'future_dreams',
    ],
  },

  travel: {
    label: 'Travel',
    icon: '✈️',
    description: 'Turn a memorable trip into a shareable keepsake.',
    sections: [
      'home',
      'gallery',
      'travel_timeline',
      'memory_map',
      'video_memories',
      'playlist',
      'travel_notes',
      'photo_highlights',
      'quotes',
    ],
  },

  proposal: {
    label: 'Proposal',
    icon: '💖',
    description: 'Create a romantic proposal or engagement memory page.',
    sections: [
      'home',
      'love_letter',
      'gallery',
      'playlist',
      'video_memories',
      'memory_map',
      'surprise_message',
      'our_story',
      'countdown',
      'future_dreams',
    ],
  },

  valentines: {
    label: "Valentine's",
    icon: '🌷',
    description: 'A sweet and romantic page for Valentine gifts.',
    sections: [
      'home',
      'love_letter',
      'gallery',
      'playlist',
      'quotes',
      'surprise_message',
      'future_dreams',
      'reasons_love_you',
      'video_memories',
      'gift_section',
    ],
  },

  mothers_day: {
    label: "Mother's Day",
    icon: '💐',
    description: 'A heartfelt page to appreciate moms.',
    sections: [
      'home',
      'gallery',
      'message_letter',
      'video_memories',
      'quotes',
      'family_message',
      'guest_messages',
      'photo_highlights',
    ],
  },

  fathers_day: {
    label: "Father's Day",
    icon: '🧡',
    description: 'A meaningful tribute page for dads.',
    sections: [
      'home',
      'gallery',
      'message_letter',
      'video_memories',
      'quotes',
      'family_message',
      'guest_messages',
      'photo_highlights',
    ],
  },
} satisfies Record<string, SiteTypeConfigEntry>;

export type SiteTypeKey = keyof typeof SITE_TYPE_CONFIG;

export const SITE_TYPES = Object.entries(SITE_TYPE_CONFIG).map(([key, value]) => ({
  key,
  label: value.label,
  icon: value.icon,
  description: value.description,
}));